HLT_triggers_prescales:
  "2024":
    BTagMu:
      BTagMu_AK8Jet300_Mu5: ${config_dir:}/prescales/ps_weight_BTagMu_AK8Jet300_Mu5_run378985_386951.json
      BTagMu_AK4Jet300_Mu5: ${config_dir:}/prescales/ps_weight_BTagMu_AK4Jet300_Mu5_run378985_386951.json
      BTagMu_AK8DiJet170_Mu5: ${config_dir:}/prescales/ps_weight_BTagMu_AK8DiJet170_Mu5_run378985_386951.json
      BTagMu_AK8Jet170_DoubleMu5: ${config_dir:}/prescales/ps_weight_BTagMu_AK8Jet170_DoubleMu5_run378985_386951.json